### PR TITLE
Redesign website from the ground up

### PR DESCRIPTION
**Pull request by worldwidepixel**
Now in astro! New look, same great taste.

astro.config.mjs and CNAME need to be changed to match ornithemc.net.

### CODE REVIEW

**Comment by worldwidepixel** [comment]
Updated CNAME and astro.config.mjs for deployment on Github Pages.
Pages setup will still have to be changed.

**Review by thdaele — COMMENTED** [review]
Looks good to me

**Review by Copetan — CHANGES_REQUESTED** [review]
Website looks good to me, but could you please remove the `.vscode` directory? I don't know exactly what's strictly necessary for the website to run and what else is just editor configuration, but please remove anything else that is just used for the editor too.

**Comment by calmilamsy** [comment]
I'd say add `.vscode` to the .gitignore to make sure this doesn't happen again.

**Comment by worldwidepixel** [comment]
@Copetan / @calmilamsy  .vscode and legacy/ removed.

**Review by Copetan — APPROVED** [review]
everything looks good now

**Comment by worldwidepixel** [comment]
🎉

**Pull request merged**
